# Generated by Django 5.2.4 on 2025-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='invitee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
