# Generated by Django 5.2.4 on 2025-07-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvite_invitee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='invitee_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
