# Generated by Django 5.2.4 on 2025-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teaminvite_invitee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='invitee_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
